runtime: nodejs18

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  MODE: production
  SERVER_PORT: 8080
  SOCKET_HOST: https://test.zvyezda.com/ws
  SERVER_HOST: https://test.zvyezda.com
  SUPA_URL: ${{ secrets.SUPA_URL }}
  SUPA_KEY: ${{ secrets.SUPA_KEY }}

entrypoint: yarn gcp:start
