name: Deploy to Google App Engine
on:
  push:
    branches:
      - main
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v2
        uses: actions/checkout@v2

      - name: Authenticate With Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: |
          mkdir -p /home/runner/docker
          echo '{"auths":{"gcr.io":{},"us.gcr.io":{},"eu.gcr.io":{},"asia.gcr.io":{}}}' > /home/runner/docker/config.json
        env:
          DOCKER_CONFIG: /home/runner/docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/max-services:latest \
            --build-arg GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
            --build-arg SUPA_URL=${{ secrets.SUPA_URL }} \
            --build-arg SUPA_KEY=${{ secrets.SUPA_KEY }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/max-services:latest
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy maxservices \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/max-services:latest \
            --platform managed \
            --region europe-west1 \
            --max-instances=1 \
            --cpu=0.5 \
            --memory=1Gi \
            --timeout=30s \
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
