name: Deploy to Google Cloud Run
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:v0.8.2,0.8.2

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/max-services:latest \
            --build-arg GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
            --build-arg SUPA_URL=${{ secrets.SUPA_URL }} \
            --build-arg SUPA_KEY=${{ secrets.SUPA_KEY }} \
            --platform linux/amd64 . \
            --push
        working-directory: ${{ github.workspace }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy maxservices \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/max-services:latest \
            --platform managed \
            --region europe-west1 \
            --max-instances=1 \
            --cpu=1 \
            --memory=2Gi \
            --timeout=30s
        working-directory: ${{ github.workspace }}
